/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;
import controle.ControladorCadastroCampanha;
import controle.ControladorCadastroPacientes;
import javax.swing.JOptionPane;
import persistência.BD;

/**
 *
 * @author cadug
 */
public class JanelaCampanhaVacinação extends javax.swing.JFrame {

    
    public JanelaCampanhaVacinação() {
        BD.criaConexão();
        initComponents();
    }

    private void informarServiçoIndisponível(){
        JOptionPane.showMessageDialog(this, "Serviço Indisponível", "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campanha_vacinacaoMenuBar = new javax.swing.JMenuBar();
        campanhasMenu = new javax.swing.JMenu();
        cadastrar_campanhaItemMenu = new javax.swing.JMenuItem();
        pacienteMenu = new javax.swing.JMenu();
        cadastrar_pacienteItemMenu = new javax.swing.JMenuItem();
        agendamentoMenu = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Campanha de Vacinação");
        setMinimumSize(new java.awt.Dimension(350, 350));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                terminarSistema(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        campanhasMenu.setText("Campanhas");

        cadastrar_campanhaItemMenu.setText("Cadastrar");
        cadastrar_campanhaItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarCampanha(evt);
            }
        });
        campanhasMenu.add(cadastrar_campanhaItemMenu);

        campanha_vacinacaoMenuBar.add(campanhasMenu);

        pacienteMenu.setText("Paciente");

        cadastrar_pacienteItemMenu.setText("Cadastrar");
        cadastrar_pacienteItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarPaciente(evt);
            }
        });
        pacienteMenu.add(cadastrar_pacienteItemMenu);

        campanha_vacinacaoMenuBar.add(pacienteMenu);

        agendamentoMenu.setText("Agendamento");

        jMenuItem3.setText("jMenuItem3");
        agendamentoMenu.add(jMenuItem3);

        jMenuItem4.setText("jMenuItem4");
        agendamentoMenu.add(jMenuItem4);

        campanha_vacinacaoMenuBar.add(agendamentoMenu);

        setJMenuBar(campanha_vacinacaoMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarCampanha(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarCampanha
        new ControladorCadastroCampanha();
    }//GEN-LAST:event_cadastrarCampanha

    private void terminarSistema(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_terminarSistema
         BD.fechaConexão();
         System.exit(0);
    }//GEN-LAST:event_terminarSistema

    private void cadastrarPaciente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarPaciente
        new ControladorCadastroPacientes();
    }//GEN-LAST:event_cadastrarPaciente

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCampanhaVacinação.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCampanhaVacinação.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCampanhaVacinação.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCampanhaVacinação.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaCampanhaVacinação().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu agendamentoMenu;
    private javax.swing.JMenuItem cadastrar_campanhaItemMenu;
    private javax.swing.JMenuItem cadastrar_pacienteItemMenu;
    private javax.swing.JMenuBar campanha_vacinacaoMenuBar;
    private javax.swing.JMenu campanhasMenu;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu pacienteMenu;
    // End of variables declaration//GEN-END:variables
}
