/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces;

/**
 *
 * @author cadug
 */
public class PainelCampanhaSarampo extends javax.swing.JPanel {

    /**
     * Creates new form PainelCampanhaSarampo
     */
    public PainelCampanhaSarampo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        intervaloLabel = new javax.swing.JLabel();
        adjuvanteCheckBox = new javax.swing.JCheckBox();
        intervaloTextField = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        intervaloLabel.setText("Intervalo entre Doses (meses)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 36, 0, 0);
        add(intervaloLabel, gridBagConstraints);

        adjuvanteCheckBox.setText("Contém Adjuvante");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 36, 44, 0);
        add(adjuvanteCheckBox, gridBagConstraints);

        intervaloTextField.setColumns(2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 6, 0, 43);
        add(intervaloTextField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

     public boolean isAdjuvante(){
        return adjuvanteCheckBox.isSelected();
    }
    
    public void setAdjuvante(boolean r){
       adjuvanteCheckBox.setSelected(r);
    }
    
    public int getIntervalo(){
        String intervalo = intervaloTextField.getText();
        if (intervalo.isEmpty()) return -1;
        else return Integer.parseInt(intervalo);
    }
    
    public void setIntervalo(String marca){
       intervaloTextField.setText(marca);
    }
    public void limparCampos(){
        intervaloTextField.setText("");
        adjuvanteCheckBox.setSelected(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox adjuvanteCheckBox;
    private javax.swing.JLabel intervaloLabel;
    private javax.swing.JTextField intervaloTextField;
    // End of variables declaration//GEN-END:variables
}
