package interfaces;

/**
 *
 * @author cadug
 */
public class PainelCampanhaCovid19 extends javax.swing.JPanel {

    /**
     * Creates new form PainelCampanhaCovid19
     */
    public PainelCampanhaCovid19() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        marcaLabel = new javax.swing.JLabel();
        marcaTextField = new javax.swing.JTextField();
        reforçoCheckBox = new javax.swing.JCheckBox();

        setLayout(new java.awt.GridBagLayout());

        marcaLabel.setText("Marca");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 72, 0, 0);
        add(marcaLabel, gridBagConstraints);

        marcaTextField.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 98;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 46, 59);
        add(marcaTextField, gridBagConstraints);

        reforçoCheckBox.setText("Dose de Reforço");
        reforçoCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reforçoCheckBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 72, 0, 0);
        add(reforçoCheckBox, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void reforçoCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reforçoCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reforçoCheckBoxActionPerformed

    public boolean isReforço(){
        return reforçoCheckBox.isSelected();
    }
    
    public void setReforço(boolean r){
       reforçoCheckBox.setSelected(r);
    }
    
    public String getMarca(){
        String marca = marcaTextField.getText();
        if (marca.isEmpty()) return null;
        else return marca;
    }
    
    public void setMarca(String marca){
       marcaTextField.setText(marca);
    }
    public void limparCampos(){
        marcaTextField.setText("");
        reforçoCheckBox.setSelected(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel marcaLabel;
    private javax.swing.JTextField marcaTextField;
    private javax.swing.JCheckBox reforçoCheckBox;
    // End of variables declaration//GEN-END:variables
}
