/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces;

/**
 *
 * @author cadug
 */
public class PainelCampanhaH1N1 extends javax.swing.JPanel {

    /**
     * Creates new form PainelCampanhaH1N1
     */
    public PainelCampanhaH1N1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        cepasLabel = new javax.swing.JLabel();
        emergencialCheckBox = new javax.swing.JCheckBox();
        cepasTextField = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        cepasLabel.setText("Número de Cepas da Influenza");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 24, 0, 0);
        add(cepasLabel, gridBagConstraints);

        emergencialCheckBox.setText("Liberada para uso emergencial");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 24, 0, 0);
        add(emergencialCheckBox, gridBagConstraints);

        cepasTextField.setColumns(2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 38, 30);
        add(cepasTextField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    public boolean isEmergencial(){
        return emergencialCheckBox.isSelected();
    }
    
    public void setEmergencial(boolean r){
       emergencialCheckBox.setSelected(r);
    }
    
    public int getCepas(){
        String cepas = cepasTextField.getText();
        if (cepas.isEmpty()) return -1;
        else return Integer.parseInt(cepas);
    }
    
    public void setCepas(String cepas){
       cepasTextField.setText(cepas);
    }
    public void limparCampos(){
        cepasTextField.setText("");
        emergencialCheckBox.setSelected(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cepasLabel;
    private javax.swing.JTextField cepasTextField;
    private javax.swing.JCheckBox emergencialCheckBox;
    // End of variables declaration//GEN-END:variables
}
